name: Go Build

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    brancges:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.6

      - name: Build Go app
        run: go build -v
