name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    brancges:
      - main
      - develop

jobs:
  test:
    name: Test code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.6

      - name: Firebase
        env:
          ENV_FILE: ${{secrets.FIREBASE}}
        run: |
          echo $ENV_FILE > foodlog-credentials.json
          cat foodlog-credentials.json
        shell: bash

      - name: Run Tests
        run: go test -v
        
  build:
    name: Build code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.6

      - name: Build Go app
        run: go build -v